### PR TITLE
New blog post: Understanding Setup by Jalani Williams.

### PR DESCRIPTION
**Pull request by jalaniw**
Added Jalani's blog post, and also fixed a few formatting issues in a previous blog post (which were preventing compilation).

### CODE REVIEW

**Comment by drbarrett** [comment]
Can you fix the links for your approvers. Currently they just point back to the post.

**Comment by drbarrett** [comment]
And nice catch on the internal links on the other post. That's going above and beyond!

**Comment by jalaniw** [comment]
Oh, yeah I can fix those --it seems like the template states that you don't need to add a URL, but then adds a hyperlink there even when a URL isn't present (e.g. in the "fifo-lru" and "ktn" blog posts). I'll add the actual links to their websites, but it might be good to have someone change the template (/template behavior) at some point.

**Comment by jalaniw** [comment]
Should be updated now!

**Comment by drbarrett** [comment]
I passed on a note about making changes to the template or instructions.

**Pull request merged**
